# Generated by Django 4.0.5 on 2022-07-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bio',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(default='', max_length=300),
        ),
    ]
