# Generated by Django 4.0.5 on 2022-07-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_bio_employee_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bio',
        ),
        migrations.AddField(
            model_name='newuser',
            name='bio',
            field=models.TextField(default='', max_length=300),
        ),
    ]
