# Generated by Django 4.0.5 on 2022-07-05 14:00

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customer_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
