# Generated by Django 4.0.5 on 2022-07-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customer_managers_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Employee'), (2, 'Customer')], default='', null=True),
        ),
    ]
